_wandb:
    value:
        cli_version: 0.19.6
        code_path: code/scripts/log_runs.py
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-x86_64
